#

@Sii_RegistroCompraVenta_HostAddress = http://localhost:5225

GET {{Sii_RegistroCompraVenta_HostAddress}}/api/RegistroCompraVenta/resumen?rut=76470584-K&year=2025&mes=3&operacion=compra
Accept: application/json

###

@Sii_RegistroCompraVenta_HostAddress = http://localhost:5225

GET {{Sii_RegistroCompraVenta_HostAddress}}/api/RegistroCompraVenta/resumen?rut=76470584-K&year=2025&mes=3&operacion=venta
Accept: application/json